# ReadTheDocs configuration file
# See https://docs.readthedocs.com/platform/stable/config-file/v2.html

version: 2

# Build environment
build:
  os: ubuntu-22.04
  tools:
    python: "3.12"

# Sphinx configuration
sphinx:
  configuration: docs/conf.py
  fail_on_warning: false

# Build formats
formats:
  - pdf
  - epub

# Python environment
python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - dev
