// import { Amplify } from 'aws-amplify';
// import { generateClient } from 'aws-amplify/data';
// import type { Schema } from '../../amplify/data/resource';

// // Import amplify_outputs.json which will be generated by Amplify sandbox
// import outputs from '../../amplify_outputs.json';

// Amplify.configure(outputs);

// export const client = generateClient<Schema>();

// Placeholder exports for when Amplify backend is not yet deployed
export const client = null as any;

// Export placeholder types for use in components
export type Corpus = any;
export type Snapshot = any;
export type FileMetadata = any;
export type CatalogMetadata = any;
export type CatalogItem = any;
