import { Amplify } from 'aws-amplify';
import { generateClient } from 'aws-amplify/data';
import type { Schema } from '../../amplify/data/resource';

// Import amplify_outputs.json which will be generated by Amplify sandbox
import outputs from '../../amplify_outputs.json';

Amplify.configure(outputs);

export const client = generateClient<Schema>();

// Export types for use in components
export type Corpus = Schema['Corpus']['type'];
export type Snapshot = Schema['Snapshot']['type'];
export type FileMetadata = Schema['FileMetadata']['type'];
export type CatalogMetadata = Schema['CatalogMetadata']['type'];
export type CatalogItem = Schema['CatalogItem']['type'];
